apiVersion: v1
kind: Service
metadata:
  name: app-secundaria-svc
  namespace: app-secundaria
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: app-secundaria
