apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-app
  template:
    metadata:
      labels:
        app: mi-app
    spec:
      containers:
      - name: mi-app-container
        image: acrpracticoandres.azurecr.io/nginx_seguro:casopractico2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-storage
          mountPath: /opt/app
      volumes:
      - name: app-storage
        persistentVolumeClaim:
          claimName: mi-app-pvc
